apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-meter
  labels:
    app.kubernetes.io/name: cluster-meter
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-meter
                port:
                  number: 80
