apiVersion: v1
kind: Service
metadata:
  name: cluster-meter
  labels:
    app.kubernetes.io/name: cluster-meter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cluster-meter
  ports:
    - name: http
      port: 80
      targetPort: 8080
