apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-meter
  namespace: argocd
spec:
  project: cluster-meter
  source:
    repoURL: https://github.com/ohanyere/cluster-meter.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-meter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
