apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-meter
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/ohanyere/cluster-meter.git
  destinations:
    - namespace: cluster-meter
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: Secret
    - group: ""
      kind: ConfigMap
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: networking.k8s.io
      kind: Ingress
